server:
  port: 8080

spring:
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.122.101:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root # 换成你自己的用户名，上面的url地址和库名也要改成自己的
    password: 123456 # 换成你自己的密码
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  data:
    redis:
      host: 192.168.122.101 # Redis服务器地址，换成你自己的Redis地址
      port: 6379
      database: 0
      password: toki123456 # Redis服务器密码，换成你自己的密码
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}  # 换成你自己的API Key
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      chat:
        options:
          model: qwen-max
    openai:
      api-key: ${DASHSCOPE_API_KEY}  # 换成你自己的API Key
      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
      chat:
        options:
          model: qwen-max-latest
          temperature: 0.9 # 随机性，越大越随机

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://192.168.122.101:8000  # MinIO服务地址，换成你自己的MinIO地址
  access-key: admin  # MinIO用户名，换成你自己的用户名
  secret-key: admin123  # MinIO密码，换成你自己的密码
  bucket-name: lease  # MinIO桶名，换成你自己的桶名

springdoc:
  default-flat-param-object: true